version: '3'

services:
  app-accountmanager:
    container_name: app-accountmanager
    build: ./accountmgr
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      - POSTGRES_DB_SERVER=postgres
      - POSTGRES_DB=accounts
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=accounts
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password