spring:
  datasource:
    url: jdbc:h2:mem:accounts;" + 
             "INIT=CREATE SCHEMA IF NOT EXISTS ACCOUNTS"
    username: admin
    password: password
  jpa:
    properties:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: create-drop
